const {Connection,PublicKey,Transaction}=require('@solana/web3.js');
const {getAssociatedTokenAddress,createTransferInstruction,TOKEN_2022_PROGRAM_ID}=require('@solana/spl-token');
(async()=>{
  const c=new Connection('https://solana-rpc.publicnode.com','confirmed');
  const mint=new PublicKey('7gZhTzquPAJ4CBPkQyyb9fUFXSiEUYpgrACXyWxBpump');
  const user=new PublicKey('Ba83tcokV1wgnA8MVQFJ341AX8dzYDvwStCqLY2upwpZ');
  const pool=new PublicKey('PFrqmXcmmsP7zfBnz9HnEnQexPLTe3uMAqwvXhLLwMe');
  const prog=TOKEN_2022_PROGRAM_ID;
  const userATA=await getAssociatedTokenAddress(mint,user,false,prog);
  const accs=await c.getParsedTokenAccountsByOwner(user,{mint});
  let out='';
  accs.value.forEach(a=>{out+='acct '+a.pubkey.toBase58()+' amount '+a.account.data.parsed.info.tokenAmount.amount+' state '+a.account.data.parsed.info.state+'\n';});
  out+='derived userATA '+userATA.toBase58()+'\n';
  const poolATA=await getAssociatedTokenAddress(mint,pool,false,prog);
  const tx=new Transaction();
  tx.add(createTransferInstruction(userATA,poolATA,user,BigInt(1000)*BigInt(1000000),[],prog));
  tx.feePayer=user; tx.recentBlockhash=(await c.getLatestBlockhash()).blockhash;
  const sim=await c.simulateTransaction(tx,undefined,false);
  out+='SIM1000 err '+JSON.stringify(sim.value.err)+'\n';
  out+=(sim.value.logs||[]).join('\n');
  require('fs').writeFileSync('_simout.txt',out);
})().catch(e=>require('fs').writeFileSync('_simout.txt','ERR '+e.message));
